### ISSUE TITLE
Image on Docker Hub is quite old

### ISSUE THREAD

**Issue by maggicl** [hypriot/rpi-swarm#10]
The official swarm image is now at v1.2.6, while this image is at v1.2.4. Although the difference is not big, the image is still 7 months old. I wonder if this is still active or not. Thanks

**Comment by firecyberice** [comment]
According to [Docker Swarm - Functionality folded directly into native Docker, no longer a standalone tool](https://docs.docker.com/manuals/) Docker Swarm is no longer provided as standalone tool. But of course you can build it on your own from source.

**Comment by maggicl** [comment]
Thanks. I'm currently using the swarm shipped in the binary.
